import React, { useState, useEffect } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import NavBar from '../components/NavBar'

export default function Home() {
  const [white, setWhite] = useState(false);

  const checkScroll = (e) => {
    const intro = document.getElementById("intro");
    if (intro.scrollTop > 20) {
      setWhite(true);
    } else {
      setWhite(false);
    }
  };

  return (
    <div className={styles.container} id="container">
      <Head>
        <title>Kū Ola</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet" /> 
      </Head>

      <NavBar white={white} />

      <div className={styles.intro} onScroll={checkScroll} id="intro">
        <div className={styles.landing}>
          <div className={styles.kukakuka}>
            <h2>Kāne Kūkākūkā</h2>
            <p>
              <strong>Open to all kāne over 18</strong>, share your manaʻo with other kāne and help improve health services for kānaka maoli!
            </p>
            <a className={styles.signup} href="https://www.uhcancercenter.org/kane" target="_blank">Sign Up for a Session!</a>
            <a className={styles.announcement } href="#announcements">Learn more about our upcoming FOA Informational Webinar!</a>
          </div>
          <div className={styles.mission_video}>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/U-z6q5tx0_4?rel=0&controls=0" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen />
          </div>
        </div>


        <div className={styles.stripe}>
          <h2>About Kū Ola</h2>
          <div className={styles.about}>
            <div className={styles.kekuni_image_desktop}>
              <Image src="/kekuni.png" layout="fill"/>
            </div>
            <p>
              &emsp; Started under the guidance of Kauka Kekuni Blaisdell, Kū Ola is committed to improving the 
              health and well-being of Native Hawaiian kāne living in Hawai‘i. In partnership with the{" "}
              <a href="https://www.uhcancercenter.org/" target="_blank">University of Hawai‘i Cancer Center</a>, we{" "}
              <a /*onMouseOver={test}*/>holomua</a> with community health <a>kūkākūkā</a> that enrich 
              kāne experiences with health services and health choices.
            </p>
            <div className={styles.uhcc_logo_desktop}>
              <Image src="/uhcc.jpg" layout="fill"/>
            </div>
          </div>
        </div>

        <div className={styles.announcements} id="announcements">
          <h2>Announcements</h2>
          <p>
            <strong>Informational Webinar</strong>: Kū Ola Program members will be available on{" "}
            <strong>Tuesday, September 12 at 1:00 PM</strong> to provide an overview of the FOA, advise on{" "}
            research concepts, respond to questions, and as needed, facilitate collaborations with investigators{" "}
            at the partnering institution; <strong><em>interested applicants are strongly encouraged to attend</em></strong>.{" "}
            Connection details are provided below.
          </p>
          <h3>Webinar Zoom Info:</h3>
          <div className={styles.zoomInfo}>
            <p><strong>Join from PC, Mac, Linux, iOS or Android</strong>: <br/><a href="https://uhcancercenter.zoom.us/j/81841474607?pwd=VU4vZ3cxenZrQ2x2V0k3aGpiRUJrUT09" target="_blank">https://uhcancercenter.zoom.us/j/81841474607?pwd=VU4vZ3cxenZrQ2x2V0k3aGpiRUJrUT09</a></p>
            <p><strong>Password</strong>: 510237</p>
          </div>
        </div>

        <div className={styles.cultural}>
          <h2>‘Ike Kūpuna</h2>
          <div className={styles.cultural_modules}>
            <div className={styles.cultural_module}>
              <h3><em>‘Ai Pono</em></h3>
              <div className={styles.cultural_video}>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/BXzBOEeX80Q?rel=0&controls=0" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen />
              </div>
              <p>
                Uncle Herbert Hoe shares his mana‘o about ‘ai pono which aims to improve the health of Native 
                Hawaiian men by incorporating a traditional Hawaiian diet. Learn how to prepare these ono dishes and 
                how they will benefit you and your ‘ohana!
              </p>
            </div>
            <div className={styles.cultural_module}>
              <h3><em>Kaula</em></h3>
              <div className={styles.cultural_video}>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/0KMJ5CQxJ88?rel=0&controls=0" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen />
              </div>
              <p>
                Sonny Kaulukuku teaches the Hawaiian art of kaula [cordage]. Kaula formed a key cornerstone of Hawaiian 
                society and used for hunting, fishing, and construction. Join us in learning about how this traditional 
                practice relates to Hawaiian health and culture.
              </p>
            </div>
            <div className={styles.cultural_module}>
              <h3><em>Pule</em></h3>
              <div className={styles.cultural_video}>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/sgAGqwU4Jeo?rel=0&controls=0" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen />
              </div>
              <p>
                We share our ‘ike on the message of Pule, and its role in the lives of our ancestors and us today. 
                Our featured kupuna kāne is Kahu Aaron Mahi, who shares his mana‘o and ‘ike on how to compose a prayer 
                to bridge the connection between kāne to Mākua.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
